### ISSUE TITLE
Add CircleCI job for Clamp-Orchestrator microsite to publish the site automatically upon commit to master

### ISSUE THREAD

**Issue by priyaaank** [clamp-orchestrator/clamp-orchestrator#5]
The Clamp microsite is built using docusaurus. Currently, the changes are made locally and the site is published as a separate step from the commit. Instead of manually publishing the site, we would like to have a circleci job publish the site whenever the code is merged to master.

**Comment by ArturBa** [comment]
Interested, could you assign me?

**Comment by priyaaank** [comment]
Hey @ArturBa. Sure! Done. You should be able to pick this one up.

**Comment by priyaaank** [comment]
Thanks for your help.

**Comment by ArturBa** [comment]
I've started working on this, could you check if CircleCi is on? It's not running on #6 and I would like to test it

**Comment by priyaaank** [comment]
We publish the [gh-pages](https://github.com/clamp-orchestrator/clamp-orchestrator/tree/gh-pages) branch of the repo to the site. I have added a basic circleci config folder and file and have enabled the app in circleci. You should be able to pull the latest master from this origin and push back your modifications.

**Comment by ArturBa** [comment]
Hi, please add an env. variable to CircleCI `DOCS_GITHUB_TOKEN`, which is a [personal access token](https://github.com/settings/tokens/) with repo scope for the target repository.

I've checked this on my master, should work now

**Comment by ArturBa** [comment]
Hi, I've checked this. It should work. Please check #8  and #9 (for no errors on gh-pages CI)
Let mi know it that works now
